AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora MySQL Cluster with RDS Proxy

Parameters:
  Environment:
    Type: String
  Group:
    Type: String
  FeatureName:
    Type: String
  DBName:
    Type: String
  DBUser:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true
  DBSubnetGroupName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: provisioned
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VpcSecurityGroupIds:
        - !Ref RDSSecurityGroup
      DatabaseName: !Ref DBName
      BackupRetentionPeriod: 1
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: sun:05:00-sun:06:00

  DBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      PubliclyAccessible: false

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDS access in VPC
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16  # Adjust for your VPC CIDR

  RDSProxyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SecretsManagerAccess
