name: Check Stack and Delete the Stack

on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'CloudFormation Stack Name'
        required: true
        
      region:
        description: 'CloudFormation region Name'
        required: true


jobs:
  check-stack:
    runs-on: ubuntu-latest
    outputs:
      stack_exists: ${{ steps.check_stack.outputs.StackExists }}
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{vars.AWS_ACCOUNT_ID == '471112768714'}}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
          #aws-region: ${{secrets.REGION}}
      
      - name: Check if Stack Exists
        id: check_stack
        run: |
          set +e
          aws cloudformation describe-stacks --stack-name "${{ github.event.inputs.stack-name }}" > stack.json 2> err.log
          if grep -q "does not exist" err.log; then
            echo "StackExists=false" >> $GITHUB_OUTPUT
          else
            echo "StackExists=true" >> $GITHUB_OUTPUT
          fi
  stop:
    needs: check-stack
    if: needs.check-stack.outputs.stack_exists == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{vars.AWS_ACCOUNT_ID == '471112768714'}}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Inform User (Stack Not Found)
        run: |
          echo "⚠️ Stack '${{ github.event.inputs.stack-name }}' not found in region '${{ github.event.inputs.region }}'."
          echo "Please verify the stack name and region"
          exit 0
          
      #- name: Stop Workflow (Stack Not Found)
       # run: |
        #  echo "❌ Stack '${{ github.event.inputs.stack-name }}' not found. Failing the pipeline."
         # exit 1

  Delete:
    needs: check-stack
    if: needs.check.outputs.stack_exists == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{vars.AWS_ACCOUNT_ID == '471112768714'}}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
          
      - name: Proceed with Deployment
        run: |
          aws cloudformation delete-stack \
            --stack-name ${{ github.event.inputs.stack-name }}
          echo "Stack found. Proceeding with deployment..."

  
