name: Check Stack and Deploy

on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'CloudFormation Stack Name'
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      stack_exists: ${{ steps.check_stack.outputs.StackExists }}
    steps:
      - name: Check if Stack Exists
        id: check_stack
        run: |
          set +e
          aws cloudformation describe-stacks --stack-name "${{ github.event.inputs.stack-name }}" > stack.json 2> err.log
          if grep -q "does not exist" err.log; then
            echo "StackExists=false" >> $GITHUB_OUTPUT
          else
            echo "StackExists=true" >> $GITHUB_OUTPUT
          fi
  stop:
    needs: check
    if: needs.check.outputs.stack_exists == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Stop Workflow (Stack Not Found)
        run: |
          echo "❌ Stack '${{ github.event.inputs.stack-name }}' not found. Failing the pipeline."
          exit 1

  deploy:
    needs: check
    if: needs.check.outputs.stack_exists == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Proceed with Deployment
        run: |
          aws cloudformation delete-stack \
            --stack-name ${{ github.event.inputs.stackName }}
          echo "Stack found. Proceeding with deployment..."

  
