name: Delete CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      stackName:
        description: 'Stack Name'
        required: true
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{vars.AWS_ACCOUNT_ID == '471112768714'}}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack \
          --stack-name ${{ github.event.inputs.stackName }} \
          --region ${{ github.event.inputs.region }}

    - name: Confirm Deletion
      run: |
        echo "Deletion initiated for stack: ${{ github.event.inputs.stackName }}"
