name: Delete CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      stack-name:
        description: "Enter the CloudFormation stack name"
        required: true
      region:
        description: "Enter the AWS region"
        required: true

jobs:
  delete-stack:
    name: Check and Delete Stack
    runs-on: ubuntu-latest

    #env:
     # AWS_REGION: ${{ github.event.inputs.region }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Check if Stack Exists
        id: check_stack
        run: |
          set +e
          aws cloudformation describe-stacks --stack-name "${{ github.event.inputs.stack-name }}" > stack.json 2> err.log
          if grep -q "does not exist" err.log; then
            echo "StackNotFound=true" >> $GITHUB_OUTPUT
          else
            echo "StackNotFound=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if Stack Not Found
        if: steps.check_stack.outputs.StackNotFound == 'true'
        run: |
          echo "❌ Stack '${{ github.event.inputs.stack-name }}' does not exist in region '${{ github.event.inputs.region }}'."
          exit 1

      - name: Delete CloudFormation Stack
        if: steps.check_stack.outputs.StackNotFound == 'false'
        run: |
          echo "✅ Stack found. Proceeding to delete..."
          aws cloudformation delete-stack --stack-name "${{ github.event.inputs.stack-name }}"
          echo "🕒 Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name "${{ github.event.inputs.stack-name }}"
          echo "✅ Stack '${{ github.event.inputs.stack-name }}' has been deleted successfully."
