# .github/workflows/read-secrets.yml
name: Read Secrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      region:                      # ✅ ADDED
        required: true
        type: string               # ✅ ADDED
    secrets:  # <-- add this block to allow passing secrets from the caller
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

    outputs:
      db-user:
        description: "Database Username"
        value: ${{ jobs.read.outputs.db-user }}
      db-password:
        description: "Database Password"
        value: ${{ jobs.read.outputs.db-password }}

jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      db-user: ${{ steps.get.outputs.db-user }}
      db-password: ${{ steps.get.outputs.db-password }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or use a parameter if you want dynamic
  
      - name: Get Secrets
        id: get
        run: |
          secret=$(aws secretsmanager get-secret-value --secret-id "myapp/${{ inputs.environment }}/secrets" --query SecretString --output text)
          echo "db-user=$(echo $secret | jq -r '.DBUser')" >> $GITHUB_OUTPUT
          echo "db-password=$(echo $secret | jq -r '.DBPassword')" >> $GITHUB_OUTPUT


---


# .github/workflows/read-secrets.yml
name: Read Secrets and Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: 
          - dev
          - staging
          - prod

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    outputs:
      db-user: ${{ steps.get-secrets.outputs.DB_USER }}
      db-pass: ${{ steps.get-secrets.outputs.DB_PASS }}
      api-key: ${{ steps.get-secrets.outputs.API_KEY }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change as needed

      - name: Get secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          secret_name="myapp/${{ github.event.inputs.environment }}/secrets"
          secret_value=$(aws secretsmanager get-secret-value --secret-id "$secret_name" --query SecretString --output text)

          DB_USER=$(echo $secret_value | jq -r '.DB_USER')
          DB_PASS=$(echo $secret_value | jq -r '.DB_PASS')
          API_KEY=$(echo $secret_value | jq -r '.API_KEY')

          echo "::set-output name=DB_USER::$DB_USER"
          echo "::set-output name=DB_PASS::$DB_PASS"
          echo "::set-output name=API_KEY::$API_KEY"

  call-deploy:
    needs: read-secrets
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      db-user: ${{ needs.read-secrets.outputs.db-user }}
      db-pass: ${{ needs.read-secrets.outputs.db-pass }}
      api-key: ${{ needs.read-secrets.outputs.api-key }}
name: Read Secrets and Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: 
          - dev
          - staging
          - prod

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    outputs:
      db-user: ${{ steps.get-secrets.outputs.DB_USER }}
      db-pass: ${{ steps.get-secrets.outputs.DB_PASS }}
      api-key: ${{ steps.get-secrets.outputs.API_KEY }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change as needed

      - name: Get secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          secret_name="myapp/${{ github.event.inputs.environment }}/secrets"
          secret_value=$(aws secretsmanager get-secret-value --secret-id "$secret_name" --query SecretString --output text)

          DB_USER=$(echo $secret_value | jq -r '.DB_USER')
          DB_PASS=$(echo $secret_value | jq -r '.DB_PASS')
          API_KEY=$(echo $secret_value | jq -r '.API_KEY')

          echo "DB_USER=$DB_USER" >> "$GITHUB_OUTPUT"
          echo "DB_PASS=$DB_PASS" >> "$GITHUB_OUTPUT"
          echo "API_KEY=$API_KEY" >> "$GITHUB_OUTPUT"

  call-deploy:
    needs: read-secrets
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      db-user: ${{ needs.read-secrets.outputs.db-user }}
      db-pass: ${{ needs.read-secrets.outputs.db-pass }}
      api-key: ${{ needs.read-secrets.outputs.api-key }}
