name: Create Deployment Environment

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name to create (e.g., dev, test)'
        required: true

jobs:
  create-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Environment using REST API
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
          ENV_NAME: ${{ github.event.inputs.env_name }}
        run: |
          echo "Creating GitHub environment: $ENV_NAME"

          curl -X PUT "https://api.github.com/repos/$REPO/environments/$ENV_NAME" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # adjust if needed

      - name: Fetch environment-specific secrets from AWS Secrets Manager
        id: fetch_secrets
        run: |
          ENV_NAME=${{ github.event.inputs.env_name }}
          SECRET_ID="myapp/${ENV_NAME}/secrets"

          echo "Fetching secret: $SECRET_ID"

          SECRET=$(aws secretsmanager get-secret-value --secret-id "$SECRET_ID" --query SecretString --output text)
          echo "$SECRET" > secrets.json

          for key in $(jq -r 'keys[]' secrets.json); do
            value=$(jq -r ".\"$key\"" secrets.json)
            echo "$key=$value" >> $GITHUB_ENV
          done

      - name: Use the secrets
        run: |
          echo "Environment: ${{ github.event.inputs.env_name }}"
          echo "DB Username: $DB_USERNAME"
          echo "DB Password: $DB_PASSWORD"
