name: Read Secrets (Reusable)

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
    outputs:
      db_user:
        description: "Database username"
        value: ${{ jobs.read-secrets.outputs.db_user }}
      db_password:
        description: "Database password"
        value: ${{ jobs.read-secrets.outputs.db_password }}

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    outputs:
      db_user: ${{ steps.set-vars.outputs.db_user }}
      db_password: ${{ steps.set-vars.outputs.db_password }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fetch DB secrets
        id: fetch-secrets
        run: |
          SECRET_NAME="myapp/${{ inputs.env_name }}/secrets"
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text)
          echo "$SECRET_JSON" > secret.json

      - name: Set outputs
        id: set-vars
        run: |
          DB_USER=$(jq -r '.username' secret.json)
          DB_PASSWORD=$(jq -r '.password' secret.json)

          echo "db_user=$DB_USER" >> $GITHUB_OUTPUT
          echo "db_password=$DB_PASSWORD" >> $GITHUB_OUTPUT
