name: Read Secrets and Deploy RDS

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name (e.g., Dev, Test)'
        required: true

jobs:
  deploy-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if needed

      - name: Fetch DB secrets from Secrets Manager
        id: fetch_secrets
        run: |
          ENV="${{ github.event.inputs.env_name }}"
          SECRET_NAME="myapp/${ENV}/secrets"
          echo "Fetching secret from: $SECRET_NAME"

          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text)
          echo "$SECRET_JSON" > secret.json

          DB_USER=$(jq -r '.username' secret.json)
          DB_PASSWORD=$(jq -r '.password' secret.json)

          echo "DBUser=$DB_USER" >> $GITHUB_ENV
          echo "DBPassword=$DB_PASSWORD" >> $GITHUB_ENV

      - name: Deploy RDS CloudFormation Stack
        run: |
          ENV_INPUT="${{ github.event.inputs.env_name }}"
          ENV_CAP="${ENV_INPUT^}"
          STACK_NAME="myapp-${ENV_INPUT}-rds"

          aws cloudformation deploy \
            --template-file Cloud/rds.yaml \
            --stack-name "$STACK_NAME" \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              Environment=$ENV_CAP \
              DBUser=$DBUser \
              DBPassword=$DBPassword \
              DBName=mydatabase \
              DBSubnetGroupName=my-subnet-group \
             # VpcId=vpc-xxxxxxxx \
             # PrivateSubnet1=subnet-aaaaaaa \
             # PrivateSubnet2=subnet-bbbbbbb
